spring:
  application:
    name: svc-appraisal-workflow
  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:eappraisal}?currentSchema=apps}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        default_schema: apps
        hbm2ddl:
          create_namespaces: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8083
integration:
  employee-master:
    base-url: ${EMPLOYEE_MASTER_BASE_URL:http://localhost:8081}
